DROP DATABASE IF EXISTS Jm_Rent;
CREATE DATABASE Jm_Rent;
SHOW DATABASES;
USE Jm_Rent;

DROP TABLE IF EXISTS Customer;
CREATE TABLE Customer(
	Customer_ID VARCHAR (8),
	Name VARCHAR (50),
	Address VARCHAR (50),
	Nic VARCHAR (12),
	Tele_Number VARCHAR(10),
CONSTRAINT PRIMARY KEY (Customer_ID)
);

DROP TABLE IF EXISTS Driver;
CREATE TABLE Driver(
	Driver_ID VARCHAR (10),
	Driver_Name VARCHAR (50),
	Daily_Cost DOUBLE (10,2),
	Nic VARCHAR (12),
	Tele_Number VARCHAR (10),
    Status VARCHAR(20),
CONSTRAINT PRIMARY KEY (Driver_ID)
);

DROP TABLE IF EXISTS Rent;
CREATE TABLE Rent(
	Rent_ID VARCHAR (8),
	Rent_Date DATE ,
	Customer_ID VARCHAR(8),
	Driver_ID VARCHAR (10),
    Total DOUBLE(15,2),
CONSTRAINT PRIMARY KEY (Rent_ID),
CONSTRAINT FOREIGN KEY (Customer_ID) REFERENCES Customer(Customer_ID) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT FOREIGN KEY (Driver_ID) REFERENCES Driver(Driver_ID)ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS Driver_Salary;
CREATE TABLE Driver_Salary(
	Name VARCHAR (50),
	Salary DOUBLE (10,2),
	Driver_ID VARCHAR (10),
    Rent_ID VARCHAR (8),
CONSTRAINT PRIMARY KEY (Driver_ID,Rent_ID),
CONSTRAINT FOREIGN KEY (Driver_ID) REFERENCES Driver(Driver_ID)ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT FOREIGN KEY (Rent_ID) REFERENCES Rent(Rent_ID)ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS Vehicle_Catergorize;
CREATE TABLE Vehicle_Catergorize(
	Catergorize_ID VARCHAR (10),
	Catergorize_Name VARCHAR (10),
CONSTRAINT PRIMARY KEY (Catergorize_ID)
);

DROP TABLE IF EXISTS Vehicle_Model;
CREATE TABLE Vehicle_Model(
	Model_ID VARCHAR (10),
	Model_Name VARCHAR (10),
CONSTRAINT PRIMARY KEY (Model_ID)
);

DROP TABLE IF EXISTS Vehicle;
CREATE TABLE Vehicle(
	Vehicle_Number VARCHAR (8),
	Model_ID VARCHAR (10),
	Cost DOUBLE (10,2),
	Description VARCHAR(50),
	Catergorize_ID VARCHAR (10),
	Status VARCHAR(20),
CONSTRAINT PRIMARY KEY (Vehicle_Number),
CONSTRAINT FOREIGN KEY (Model_ID) REFERENCES Vehicle_Model(Model_ID)ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT FOREIGN KEY (Catergorize_ID) REFERENCES Vehicle_Catergorize(Catergorize_ID)ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS Repair_Vehicle;
CREATE TABLE Repair_Vehicle(
	Vehicle_Number VARCHAR (8),
	Repair_Vehicle_ID VARCHAR (10),
	Status VARCHAR(20),
CONSTRAINT PRIMARY KEY (Repair_Vehicle_ID),
CONSTRAINT FOREIGN KEY (Vehicle_Number) REFERENCES Vehicle(Vehicle_Number)ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS Rent_Detail;
CREATE TABLE Rent_Detail(
	Rent_ID VARCHAR (8),
	Rent_Date DATE ,
	Return_Date DATE,
	Driver_ID VARCHAR (10),
	Vehicle_Number VARCHAR (8),
	Total DOUBLE(15,2),
    Status VARCHAR(20),
CONSTRAINT PRIMARY KEY (Rent_ID,Vehicle_Number),
CONSTRAINT FOREIGN KEY (Rent_ID) REFERENCES Rent(Rent_ID)ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT FOREIGN KEY (Vehicle_Number) REFERENCES Vehicle(Vehicle_Number)ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS `User`;
CREATE TABLE `User`(
	User_Name VARCHAR (10),
	`Name` VARCHAR (50) ,
	Address VARCHAR (50),
	Tele_No VARCHAR (10),
    `Role` VARCHAR (8),
	User_Password VARCHAR(100),
CONSTRAINT PRIMARY KEY (User_Name)
);

DROP TABLE IF EXISTS Login;
CREATE TABLE Login(
	User_Name VARCHAR (10),
	Login_ID VARCHAR (10),
	User_Password VARCHAR(100),
CONSTRAINT PRIMARY KEY (Login_ID),
CONSTRAINT FOREIGN KEY (User_Name) REFERENCES `User`(User_Name)ON DELETE CASCADE ON UPDATE CASCADE
);

SHOW TABLES ;
DESC Customer;
SELECT * FROM Customer;
ALTER TABLE Repair_Vehicle DROP COLUMN Description;
INSERT INTO `User` VALUES ("jeewa","jeewantha madushan","horana","0779964839","Admin",md5("jeewa"));
ALTER TABLE Rent ADD Rent_ID VARCHAR(10) PRIMARY KEY,
ADD CONSTRAINT FOREIGN KEY (Rent_ID) REFERENCES Rent(Rent_ID)ON DELETE CASCADE ON UPDATE CASCADE;


